name: yaml-language-server
version: '1.15.0'
summary: YAML Language Server
description: |
  Features
  1. YAML validation:
    * Detects whether the entire file is valid yaml
  2. Validation:
    * Detects errors such as:
      * Node is not found
      * Node has an invalid key node type
      * Node has an invalid type
      * Node is not a valid child node
    * Detects warnings such as:
      * Node is an additional property of parent
  3. Auto completion:
    * Auto completes on all commands
    * Scalar nodes autocomplete to schema's defaults if they exist
  4. Hover support:
    * Hovering over a node shows description if available
  5. Document outlining:
    * Shows a complete document outline of all nodes in the document

grade: stable
confinement: strict
base: core22

apps:
  yaml-language-server:
    command: bin/yaml-language-server
    plugs:
      - network

parts:
  yaml-language-server:
    plugin: npm
    source: https://github.com/redhat-developer/yaml-language-server.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    npm-node-version: 22.13.0
    npm-include-node: true
    override-build: |
      # this will just install node and run npm install -g into
      # CRAFT_PARTS_INSTALL - we need to also actually compile the typescript
      # source into javascript
      craftctl default
      # ensure devDependencies get installed by unsetting NODE_ENV as production
      unset NODE_ENV
      npm install
      npm run compile
      cp -r out $SNAPCRAFT_PART_INSTALL/lib/node_modules/yaml-language-server/
