name: yaml-language-server
version: '1.14.0'
summary: YAML Language Server
description: |
  Features
  1. YAML validation:
    * Detects whether the entire file is valid yaml
  2. Validation:
    * Detects errors such as:
      * Node is not found
      * Node has an invalid key node type
      * Node has an invalid type
      * Node is not a valid child node
    * Detects warnings such as:
      * Node is an additional property of parent
  3. Auto completion:
    * Auto completes on all commands
    * Scalar nodes autocomplete to schema's defaults if they exist
  4. Hover support:
    * Hovering over a node shows description if available
  5. Document outlining:
    * Shows a complete document outline of all nodes in the document

grade: stable
confinement: strict
base: core22

apps:
  yaml-language-server:
    command: bin/yaml-language-server
    plugs:
      - network
      - home

parts:
  yaml-language-server:
    plugin: npm
    source: https://github.com/redhat-developer/yaml-language-server.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    npm-include-node: true
    npm-node-version: 20.11.0
    override-build: |
      snapcraftctl build
      corepack yarn install
      corepack yarn run build
      cp -r out $SNAPCRAFT_PART_INSTALL/lib/node_modules/yaml-language-server/
